site_name: Web Crawling
site_author: "Vu Anh"
google_analytics: ["UA-68978617-1", "magizbox.com"]

pages:
- "<span class='fa fa-home'></span> Home": "index.md"
- "Overview":
  - "Web Cralwer": "web_crawler.md"
  - "Crawling": "crawling.md"
  - "New Approach": "new_approach.md"
- "Scrapy":
  - "Getting Started": "scrapy.md"
- "Apache Nutch":
  - "Getting Started": "nutch.md"
  - "Architecture": "nutch_architecture.md"
  - "Develop Nutch in IntellIJ": "nutch_intellij.md"
- "<span class='fa fa-rss'></span> News": "feed.md"

markdown_extensions:
    - footnotes

extra_css:
  - components/magiz-c-book/src/book.css
  - components/magiz-c-course/src/course.css
  - components/magiz-c-video/src/video.css
  - components/magiz-c-benchmark/src/benchmark.css
  - components/magiz-c-paper/src/paper.css
  - components/magiz-c-feed/src/feed.css

extra_javascript:
  - components/underscore/underscore.js
  - components/magiz-c-book/src/gspreadsheet.js
  - components/magiz-c-paper/src/paper.js
  - components/magiz-c-course/src/course.js
  - components/magiz-c-benchmark/src/benchmark.js
  - components/magiz-c-benchmark/src/bootstrap-popup.js
  - components/magiz-c-book/src/book.js
  - components/magiz-c-video/src/video.js
  - components/magiz-c-feed/src/feed.js
